name: HIRE-AGENT

on:
  push:
    branches: [ "main"]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set execute permission for deploy.sh
      run: docker-compose -f docker-compose.yaml up -d --build

    - name: Remove build cache
      run: docker system prune -a -f

